---
- name: Datadog
  block:
  - name: Add helm repository
    kubernetes.core.helm_repository:
      name: datadog
      repo_url: https://helm.datadoghq.com

  - name: Add API key
    shell: |
      kubectl create secret generic datadog-secret --from-literal api-key={{ api_key }} --namespace=monitoring

  - name: Install datadog/datadog-operator
    kubernetes.core.helm:
      name: datadog-operator
      chart_ref: datadog/datadog-operator
      release_namespace: monitoring
      create_namespace: true

  - name: Copy config
    template:
      src: datadog-agent.yml.j2
      dest: /tmp
      owner: root
      group: root
      mode: "0644"

  - name: Apply config
    shell: kubectl apply -f /tmp/datadog-agent.yml
  when: dd_api_key is defined
